Homework2
made-ml-in-prod-2021/balan pull request #3
Opened 2021-05-19 21:09 UTC by balan

Приветствую! Добавляю домашнее задание. 
Ниже обозначены проделанные пункты:

0) [+0/0] ветку назовите homework2, положите код в папку online_inference

1) [+3/3] Оберните inference вашей модели в rest сервис(вы можете использовать как FastAPI, так и flask, другие желательно не использовать, дабы не плодить излишнего разнообразия для проверяющих), должен быть endpoint /predict (3 балла)

2) [+3/3] Напишите тест для /predict  (3 балла) (https://fastapi.tiangolo.com/tutorial/testing/, https://flask.palletsprojects.com/en/1.1.x/testing/)

3) [+2/2] Напишите скрипт, который будет делать запросы к вашему сервису -- 2 балла

4) [+3/3] Сделайте валидацию входных данных (например, порядок колонок не совпадает с трейном, типы не те и пр, в рамках вашей фантазии)  (вы можете сохранить вместе с моделью доп информацию, о структуре входных данных, если это нужно) -- 3 доп балла
https://fastapi.tiangolo.com/tutorial/handling-errors/ -- возращайте 400, в случае, если валидация не пройдена

5) [+4/4] Напишите dockerfile, соберите на его основе образ и запустите локально контейнер(docker build, docker run), внутри контейнера должен запускать сервис, написанный в предущем пункте, закоммитьте его, напишите в readme корректную команду сборки (4 балл)

6) [+0/3] Оптимизируйте размер docker image (3 доп балла) (опишите в readme.md что вы предприняли для сокращения размера и каких результатов удалось добиться)  -- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

7) [+0/2] опубликуйте образ в https://hub.docker.com/, используя docker push (вам потребуется зарегистрироваться) (2 балла)

8) [+1/1] напишите в readme корректные команды docker pull/run, которые должны привести к тому, что локально поднимется на inference ваша модель (1 балл)
Убедитесь, что вы можете протыкать его скриптом из пункта 3

5) [+1/1] проведите самооценку -- 1 доп балл
6) [✅] создайте пулл-реквест и поставьте label -- hw2

Получилось баллов: 17

To-do: если успею, добавлю образ докера на https://hub.docker.com/ и оптимизирую размер.

2021-05-27 14:26 UTC, Mikhail-M requested changes
Добейтесь, чтобы не было кода первого дз в этом реквесте

2021-05-28 09:20 UTC, garistvlad requested changes
Добавил некоторые комментарии по коду, но в целом все отлично.
Два основных комментария:
1. Реализовать пункт 4 требований
2. Как Михаил и написал, убрать в отдельную ветку / Pull Request код из ДЗ №1

На текущий момент оценка - **14 баллов**

2021-05-28 09:20 UTC, garistvlad commented on online_inference/app.py
> +        raise HTTPException(status_code=400)
Вся структура ML модели, набор признаков и тд описаны в src, а функция make_predict() находится тут в app.py - модуле, реализующем логику API.
Думаю, правильнее было бы убрать из app.py логику ML модели и вынести make_predict(), например, в src.

2021-05-28 09:20 UTC, garistvlad commented on online_inference/src/entities.py
> +    features: List[str]
В пункте 4 требовалось: "Сделайте валидацию входных данных (например, порядок колонок не совпадает с трейном, типы не те и пр, в рамках вашей фантазии)"

Думаю, проверку можно было сделать как на уровне модели данных (это кажется самый правильный вариант), либо уже после чтения данных в момент вызова predict() (так тоже годится). Пример добавления валидаторов в модель данных можно посмотреть тут: https://pydantic-docs.helpmanual.io/usage/validators/
Для того, чтобы реализовать эту проверку, возможно придется поменять поля в HeartDiseaseModel с data на более развернутый список. Пока за пункт 4 не могу поставить баллы

2021-05-28 09:20 UTC, garistvlad commented on online_inference/app.py
> +    return make_predict(request.data, request.features, model)
мелочный комментарий, но все же я бы endpoint /predict реализовывал через POST метод (вместо GET) - это своего рода стандарт для RestAPI, когда ты отправляешь данные на сервер и ожидаешь какой-то результат в ответе.

2021-05-28 19:57 UTC, balan commented
Увидел ваши комментарии, на выходных внесу исправления

2021-05-30 20:49 UTC, balan commented
Добрый вечер, сделал несколько исправлений:
- убрал код первого дз из реквеста
- поменял реализацию метода predict на POST
- поправил валидацию входных данных (пункт 4 задания), вынес её в отдельный модуль вне app.py
- залил docker image на Docker Hub
- сделал оптимизацию размера контейнера

Также поправил файл readme и отразил там выполненные пункты задания.
Итого получилось: 22 балла

2021-06-06 10:05 UTC, Mikhail-M approved these changes
Оптимизация: 1.5
Валидация: 1.5 (скромненько сделано)
Тесты: 2(так как нужен файл с моделью для тестов)
Баллы: 18

2021-06-07 22:21 UTC, merged